version: '3.8'

services:
  classifier:
    build:
      context: cmd/classifier
      dockerfile: Dockerfile
    ports:
      - "7860:${CLASSIFIER_PORT:-7860}"
    environment:
      - USE_CUDA=${USE_CUDA:-false}
      - PORT=${CLASSIFIER_PORT:-7860}
    networks:
      - inkbunny-network
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: all
  #           capabilities: [ gpu ]

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - PREDICT_URL=${PREDICT_URL:-http://classifier:7860/predict}
      - SKIP_LOAD=${SKIP_LOAD:-false}
    volumes:
      - server_data:/app/data
    depends_on:
      - classifier
    networks:
      - inkbunny-network

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
      target: telegram
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_REFRESH_RATE=${TELEGRAM_REFRESH_RATE}
      - TELEGRAM_SID=${TELEGRAM_SID}
      - TELEGRAM_ENCRYPT_KEY=${TELEGRAM_ENCRYPT_KEY}
      - TELEGRAM_CLASSIFY=${TELEGRAM_CLASSIFY}
      - TELEGRAM_CLASSES=${TELEGRAM_CLASSES}
    volumes:
      - telegram_data:/app/data
    depends_on:
      - classifier
      - server
    networks:
      - inkbunny-network

volumes:
  server_data:
    driver: local
  telegram_data:
    driver: local

networks:
  inkbunny-network:
    driver: bridge 